import React,{useEffect,useState} from 'react';
import {api} from './api';
export default function Connection(){
  const [state,setState]=useState(null),[token,setToken]=useState(''),[error,setError]=useState('');
  async function refresh(){try{setState(await api('/collector'));}catch(e){setError(e.message);}}
  useEffect(()=>{void refresh();const id=setInterval(refresh,15000);return()=>clearInterval(id);},[]);
  async function pair(){try{setError('');const result=await api('/collector/pair',{method:'POST',body:{}});setToken(result.token);await refresh();}catch(e){setError(e.message);}}
  async function revoke(){try{await api('/collector/revoke',{method:'POST',body:{}});setToken('');await refresh();}catch(e){setError(e.message);}}
  return <section className="panel channel-card"><h2>Conectar o navegador</h2><p>O teste da página pública funcionou no navegador. O acesso direto do servidor foi bloqueado. A extensão lê somente os resultados visíveis e pausa em verificações de segurança.</p><div className="note"><strong>Estado: {state?.status||'Consultando…'}</strong><br/>Última leitura: {state?.last_read?new Date(state.last_read).toLocaleString('pt-BR'):'Nenhuma leitura recebida'}</div><ol style={{lineHeight:1.9,color:'#cbd7de'}}><li>No Chrome ou Edge, abra a página de extensões e ative o modo de desenvolvedor.</li><li>Escolha “Carregar sem compactação” e selecione a pasta <strong>extension</strong> dentro do projeto Latam Market Radar.</li><li>Gere a chave abaixo e cole no painel da extensão. Clique “Iniciar”.</li><li>Mantenha o Radar local, o navegador e a aba dedicada do mercado abertos.</li></ol><p>A extensão 1.2.0 busca cada item com meta de 5 minutos, em fila. Consultas demoradas, suspensão ou o limite de consultas podem atrasar esse intervalo. Só são compatíveis monitoramentos por <strong>nome exato, sem ID, sem refino e sem filtro de grau</strong>. Registra o menor preço encontrado em até 5 páginas por consulta e só salva novamente quando esse preço muda. Não garante cobrir todas as ofertas.</p><p>A chave permite apenas consultar seus monitoramentos compatíveis e enviar leituras. Expira em 7 dias. Gere outra para revogar a anterior.</p><div className="heading-actions"><button className="button primary" onClick={pair}>Gerar chave de conexão</button><button className="button secondary" onClick={revoke}>Revogar conexão</button></div>{token&&<label style={{marginTop:20}}>Copie a chave e cole na extensão<input readOnly value={token} onFocus={e=>e.target.select()}/></label>}{state?.recent_reads?.length>0&&<div style={{marginTop:24}}><h3>Últimas tentativas por item</h3>{state.recent_reads.map((r,i)=><div className="note" key={i}><strong>{r.item_name}</strong><br/>{r.detail}<br/><small>{new Date(r.received_at).toLocaleString('pt-BR')} · Extensão {r.reader_version}</small></div>)}</div>}{error&&<p className="error">{error}</p>}</section>;
}
